name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Update composer.json
      run: composer update

    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer test
